```{r}
#packages
{
  packages_github <- c()
  
  installed_packages <- packages_github %in% rownames(installed.packages())
  if (any(installed_packages == FALSE)) {
    devtools::install_github(packages_github[!installed_packages])
  }
  
  # Packages loading
  invisible(lapply(sub(".*?/", "", packages_github), library, character.only = TRUE))
  
  packages <- c("dplyr","ggplot2","quantmod","zoo","plyr","forecast","tseries","tidyverse","furrr")
  
  # Install packages not yet installed
  installed_packages <- packages %in% rownames(installed.packages())
  if (any(installed_packages == FALSE)) {
    install.packages(packages[!installed_packages])
  }
  
  # Packages loading
  invisible(lapply(packages, library, character.only = TRUE))
  
}

```


```{r}
#data
lacondos <- read.csv("C:/Users/User/Documents/wiki/wiki/Excel/LACondos.csv",row.names=1)
```

```{r}
#vars

dates <- as_data_frame(as.Date(rownames(lacondos), format =  "%m/%d/%Y"))
f = periodicity(dates$value)

fresult = switch(  
  f$scale,  
  "monthly"= 12,  
  "daily"= 252,  
  "quarterly"= 4,  
  "weekly"= 52,
)  

aggresult = switch(  
  f$scale,  
  "monthly"= "Month",  
  "daily"= "Day",  
  "quarterly"= "Quarter",  
  "weekly"= "Week",
)

aset = switch(  
  f$scale,  
  "monthly"= c("Month" = "Month"),  
  "daily"= c("Day" = "Day"),  
  "quarterly"= c("Quarter" = "Quarter"),  
  "weekly"= c("Week" = "Week"),
) 

{
  training <- nrow(lacondos)*.7
  validation <- training-round(nrow(lacondos)*.7*.3,0)
  holdout <- nrow(lacondos)-nrow(lacondos)*.7+validation
}

#vars
{
  variable_of_interest="LXXRCSA"
  N=nrow(lacondos)
  alpha = .05
  significant_threshold=(exp(2*-qnorm((1-alpha)/2)/sqrt(N-3)-1))/(exp(2*-qnorm((1-alpha)/2)/sqrt(N-3)+1))
}


```

```{r}
timeseries_lacondo = lacondos[,1,drop=FALSE]
plot(as.ts(timeseries_lacondo))
```


```{r}
#ma_nonlinear_additive_lacondos = as.data.frame(ma(lacondos, order = fresult, centre=F))
#cma_cycle_trend_nonlinear_additive_lacondos = as.data.frame(ma(ma_nonlinear_additive_lacondos, order = fresult/2, centre=F))
cma_cycle_trend_nonlinear_additive_lacondos = as.data.frame(ma(lacondos, order = fresult, centre=T))

ma(c(1,2,3,4),order = 2, centre=T)

plot(as.ts(timeseries_lacondo))
lines(cma_cycle_trend_nonlinear_additive_lacondos)
```

```{r}

```


```{r}
CF_lm <- lm(V1 ~., data=cbind(rownames(na.omit(cma_cycle_trend_nonlinear_additive_lacondos))[1]:tail(rownames(na.omit(cma_cycle_trend_nonlinear_additive_lacondos)),1),na.omit(cma_cycle_trend_nonlinear_additive_lacondos)))
CMAT_lacondos = CF_lm$fitted.values
```

```{r}
CF_multiplicative_lacondos = cma_cycle_trend_nonlinear_additive_lacondos/CMAT_lacondos

CF_additive_lacondos = merge(as.matrix(cma_cycle_trend_nonlinear_additive_lacondos),as.data.frame(CMAT_lacondos),by=0, all=TRUE)
rownames(CF_additive_lacondos) <- CF_additive_lacondos$Row.names

CF_additive_lacondos <- CF_additive_lacondos[order(as.numeric(row.names(CF_additive_lacondos))),]

CF_additive_lacondos <- CF_additive_lacondos[,2]/CF_additive_lacondos[,3]

M_SI <- colMeans(t(matrix(as.matrix(timeseries_lacondo/cma_cycle_trend_nonlinear_additive_lacondos),nrow=fresult)),na.rm=TRUE)
M_SI <- M_SI/mean(M_SI)
plot(rep(M_SI,fresult),type="l")

A_SI <- colMeans(t(matrix(as.matrix(timeseries_lacondo-cma_cycle_trend_nonlinear_additive_lacondos),nrow=fresult)),na.rm=TRUE)
A_SI <- A_SI-mean(A_SI)
plot(rep(A_SI,fresult),type="l")
```

```{r}
detrend_nonlinear_additive_lacondos = timeseries_lacondo - cma_cycle_trend_nonlinear_additive_lacondos
plot(as.ts(detrend_nonlinear_additive_lacondos))
```


```{r}
seasonal_nonlinear_additive_lacondos = colMeans(t(matrix(as.matrix(detrend_nonlinear_additive_lacondos),nrow=fresult)), na.rm =T)
plot(as.ts(rep(seasonal_nonlinear_additive_lacondos,fresult)))
```
```{r}

```


```{r}
random_nonlinear_additive_lacondos = matrix(ts(timeseries_lacondo,frequency=fresult) - ts(cma_cycle_trend_nonlinear_additive_lacondos,frequency=fresult) - 
ts(matrix(ts(seasonal_nonlinear_additive_lacondos,start=c(0,1),frequency=fresult,end=c(floor(nrow(timeseries_lacondo)/fresult),(nrow(timeseries_lacondo)%%fresult)))),,frequency=fresult)
)
plot(as.ts(random_nonlinear_additive_lacondos))
```


```{r}
recomposed_nonlinear_additive_lacondos = as.matrix(cma_cycle_trend_nonlinear_additive_lacondos) + matrix(ts(seasonal_nonlinear_additive_lacondos,start=c(0,1),frequency=fresult,end=c(floor(nrow(timeseries_lacondo)/fresult),(nrow(timeseries_lacondo)%%fresult)))) #+ random_nonlinear_additive_lacondos

recomposed_linear_additive_lacondos = as.matrix(cma_cycle_trend_nonlinear_additive_lacondos) + matrix(ts(A_SI,start=c(0,1),frequency=fresult,end=c(floor(nrow(timeseries_lacondo)/fresult),(nrow(timeseries_lacondo)%%fresult)))) + as.matrix(CF_additive_lacondos)

plot(as.ts(recomposed_nonlinear_additive_lacondos))
lines(as.ts(recomposed_linear_additive_lacondos))
```


```{r}
ts_nonlinear_additive_lacondos = ts(timeseries_lacondo, frequency = fresult)
decompose_nonlinear_additive_lacondos = decompose(ts_nonlinear_additive_lacondos, "additive")
plot(as.ts(decompose_nonlinear_additive_lacondos$seasonal))
plot(as.ts(decompose_nonlinear_additive_lacondos$trend))
plot(as.ts(decompose_nonlinear_additive_lacondos$random))
plot(decompose_nonlinear_additive_lacondos)
```


```{r}
ts_nonlinear_additive_lacondos = ts(timeseries_lacondo, frequency = fresult)
dim(ts_nonlinear_additive_lacondos)<-NULL
stl_nonlinear_additive_lacondos = stl

stl_nonlinear_additive_lacondos = stl(ts_nonlinear_additive_lacondos, "periodic",robust = TRUE)

seasonal_stl_nonlinear_additive_lacondos <- stl_nonlinear_additive_lacondos$time.series[,1]
trend_stl_nonlinear_additive_lacondos <- stl_nonlinear_additive_lacondos$time.series[,2]
random_stl_nonlinear_additive_lacondos <- stl_nonlinear_additive_lacondos$time.series[,2]

plot(ts_nonlinear_additive_lacondos)
plot(as.ts(seasonal_stl_nonlinear_additive_lacondos))
plot(trend_stl_nonlinear_additive_lacondos)
plot(random_stl_nonlinear_additive_lacondos)
plot(stl_nonlinear_additive_lacondos)
```

```{r}
 
```

